[2025-01-29T11:13:01.169+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T11:13:01.296+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [queued]>
[2025-01-29T11:13:01.319+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [queued]>
[2025-01-29T11:13:01.322+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T11:13:01.394+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): product_Load_redshift> on 2025-01-29 11:12:34.645629+00:00
[2025-01-29T11:13:01.576+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1766) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T11:13:01.592+0000] {standard_task_runner.py:72} INFO - Started process 1781 to run task
[2025-01-29T11:13:01.623+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'product_Load_redshift', 'manual__2025-01-29T11:12:34.645629+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp79hogp91']
[2025-01-29T11:13:01.691+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask product_Load_redshift
[2025-01-29T11:13:02.455+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T11:12:34.645629+00:00 [running]> on host ae52aba2dca2
[2025-01-29T11:13:03.585+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='product_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T11:12:34.645629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T11:12:34.645629+00:00'
[2025-01-29T11:13:03.629+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T11:13:06.420+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T11:13:06.449+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T11:13:06.525+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T11:13:06.527+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=product_Load_redshift, run_id=manual__2025-01-29T11:12:34.645629+00:00, execution_date=20250129T111234, start_date=20250129T111301, end_date=20250129T111306
[2025-01-29T11:13:06.650+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T11:13:06.691+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-01-29T11:13:06.836+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T11:13:06.854+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
