[2025-01-29T11:55:36.322+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T11:55:36.347+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.order_Load_redshift manual__2025-01-29T11:54:44.297483+00:00 [queued]>
[2025-01-29T11:55:36.358+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.order_Load_redshift manual__2025-01-29T11:54:44.297483+00:00 [queued]>
[2025-01-29T11:55:36.359+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T11:55:36.376+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): order_Load_redshift> on 2025-01-29 11:54:44.297483+00:00
[2025-01-29T11:55:36.389+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2438) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T11:55:36.393+0000] {standard_task_runner.py:72} INFO - Started process 2447 to run task
[2025-01-29T11:55:36.390+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'order_Load_redshift', 'manual__2025-01-29T11:54:44.297483+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpzmv6p2ax']
[2025-01-29T11:55:36.395+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask order_Load_redshift
[2025-01-29T11:55:36.471+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.order_Load_redshift manual__2025-01-29T11:54:44.297483+00:00 [running]> on host ae52aba2dca2
[2025-01-29T11:55:36.600+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='order_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T11:54:44.297483+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T11:54:44.297483+00:00'
[2025-01-29T11:55:36.602+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T11:55:46.895+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T11:55:46.896+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T11:55:46.912+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T11:55:46.913+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=order_Load_redshift, run_id=manual__2025-01-29T11:54:44.297483+00:00, execution_date=20250129T115444, start_date=20250129T115536, end_date=20250129T115546
[2025-01-29T11:55:46.972+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T11:55:46.992+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T11:55:46.995+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
