[2025-01-29T11:55:16.847+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T11:55:16.971+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.customer_Transform manual__2025-01-29T11:54:44.297483+00:00 [queued]>
[2025-01-29T11:55:17.024+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.customer_Transform manual__2025-01-29T11:54:44.297483+00:00 [queued]>
[2025-01-29T11:55:17.026+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T11:55:17.140+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): customer_Transform> on 2025-01-29 11:54:44.297483+00:00
[2025-01-29T11:55:17.412+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2391) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T11:55:17.426+0000] {standard_task_runner.py:72} INFO - Started process 2410 to run task
[2025-01-29T11:55:17.437+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'customer_Transform', 'manual__2025-01-29T11:54:44.297483+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpbdr1n49x']
[2025-01-29T11:55:17.459+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask customer_Transform
[2025-01-29T11:55:18.530+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.customer_Transform manual__2025-01-29T11:54:44.297483+00:00 [running]> on host ae52aba2dca2
[2025-01-29T11:55:19.523+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='customer_Transform' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T11:54:44.297483+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T11:54:44.297483+00:00'
[2025-01-29T11:55:19.527+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T11:55:27.502+0000] {logging_mixin.py:190} INFO - <class 'pandas.core.frame.DataFrame'>
Index: 638 entries, 0 to 2586
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Customer ID    638 non-null    object
 1   Customer Name  638 non-null    object
 2   Segment        638 non-null    object
dtypes: object(3)
memory usage: 19.9+ KB
[2025-01-29T11:55:27.504+0000] {logging_mixin.py:190} INFO - None
[2025-01-29T11:55:28.721+0000] {job.py:229} INFO - Heartbeat recovered after 12.38 seconds
[2025-01-29T11:55:29.736+0000] {logging_mixin.py:190} INFO - !_upload_to_S3_complete_!
[2025-01-29T11:55:29.742+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T11:55:29.787+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T11:55:29.792+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=customer_Transform, run_id=manual__2025-01-29T11:54:44.297483+00:00, execution_date=20250129T115444, start_date=20250129T115516, end_date=20250129T115529
[2025-01-29T11:55:29.965+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T11:55:30.047+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T11:55:30.055+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
