[2025-01-29T12:19:00.729+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T12:19:00.915+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [queued]>
[2025-01-29T12:19:00.945+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [queued]>
[2025-01-29T12:19:00.946+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T12:19:00.999+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): product_Load_redshift> on 2025-01-29 12:17:52.370778+00:00
[2025-01-29T12:19:01.240+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2782) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T12:19:01.407+0000] {standard_task_runner.py:72} INFO - Started process 2812 to run task
[2025-01-29T12:19:01.376+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'product_Load_redshift', 'manual__2025-01-29T12:17:52.370778+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpvezmgxaz']
[2025-01-29T12:19:01.421+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask product_Load_redshift
[2025-01-29T12:19:02.480+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.product_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [running]> on host ae52aba2dca2
[2025-01-29T12:19:03.346+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='product_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T12:17:52.370778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T12:17:52.370778+00:00'
[2025-01-29T12:19:03.391+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T12:19:12.963+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T12:19:13.157+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T12:19:14.026+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T12:19:14.047+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=product_Load_redshift, run_id=manual__2025-01-29T12:17:52.370778+00:00, execution_date=20250129T121752, start_date=20250129T121900, end_date=20250129T121914
[2025-01-29T12:19:14.663+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T12:19:15.383+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T12:19:15.393+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-29T12:19:16.573+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
