[2025-01-29T10:07:11.224+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T10:07:11.255+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.location_Transform manual__2025-01-29T10:06:58.825694+00:00 [queued]>
[2025-01-29T10:07:11.268+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.location_Transform manual__2025-01-29T10:06:58.825694+00:00 [queued]>
[2025-01-29T10:07:11.269+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T10:07:11.292+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): location_Transform> on 2025-01-29 10:06:58.825694+00:00
[2025-01-29T10:07:11.329+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=792) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T10:07:11.334+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'location_Transform', 'manual__2025-01-29T10:06:58.825694+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp558r93fb']
[2025-01-29T10:07:11.344+0000] {standard_task_runner.py:72} INFO - Started process 800 to run task
[2025-01-29T10:07:11.345+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask location_Transform
[2025-01-29T10:07:13.080+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.location_Transform manual__2025-01-29T10:06:58.825694+00:00 [running]> on host ae52aba2dca2
[2025-01-29T10:07:13.455+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='location_Transform' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T10:06:58.825694+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T10:06:58.825694+00:00'
[2025-01-29T10:07:13.457+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T10:07:15.036+0000] {logging_mixin.py:190} INFO - <class 'pandas.core.frame.DataFrame'>
Index: 399 entries, 0 to 2563
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Postal Code  399 non-null    int64 
 1   Country      399 non-null    object
 2   Region       399 non-null    object
 3   State        399 non-null    object
 4   City         399 non-null    object
dtypes: int64(1), object(4)
memory usage: 18.7+ KB
[2025-01-29T10:07:15.037+0000] {logging_mixin.py:190} INFO - None
[2025-01-29T10:07:15.576+0000] {logging_mixin.py:190} INFO - !_upload_to_S3_complete_!
[2025-01-29T10:07:15.580+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T10:07:15.682+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T10:07:15.684+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=location_Transform, run_id=manual__2025-01-29T10:06:58.825694+00:00, execution_date=20250129T100658, start_date=20250129T100711, end_date=20250129T100715
[2025-01-29T10:07:15.832+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T10:07:15.914+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T10:07:16.353+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-01-29T10:07:16.721+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
