[2025-01-29T10:54:26.547+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T10:54:26.573+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.time_Load_redshift manual__2025-01-29T10:53:39.199622+00:00 [queued]>
[2025-01-29T10:54:26.591+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.time_Load_redshift manual__2025-01-29T10:53:39.199622+00:00 [queued]>
[2025-01-29T10:54:26.592+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-01-29T10:54:26.617+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): time_Load_redshift> on 2025-01-29 10:53:39.199622+00:00
[2025-01-29T10:54:26.632+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'time_Load_redshift', 'manual__2025-01-29T10:53:39.199622+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp0s7d3ybq']
[2025-01-29T10:54:26.631+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1523) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T10:54:26.638+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask time_Load_redshift
[2025-01-29T10:54:26.639+0000] {standard_task_runner.py:72} INFO - Started process 1525 to run task
[2025-01-29T10:54:26.740+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.time_Load_redshift manual__2025-01-29T10:53:39.199622+00:00 [running]> on host ae52aba2dca2
[2025-01-29T10:54:26.857+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='time_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T10:53:39.199622+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T10:53:39.199622+00:00'
[2025-01-29T10:54:26.859+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T10:54:38.867+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T10:54:38.869+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T10:54:38.884+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T10:54:38.885+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=time_Load_redshift, run_id=manual__2025-01-29T10:53:39.199622+00:00, execution_date=20250129T105339, start_date=20250129T105426, end_date=20250129T105438
[2025-01-29T10:54:38.950+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T10:54:38.972+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T10:54:38.975+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
