[2025-01-29T12:21:42.746+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T12:21:42.768+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_dag.order_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [queued]>
[2025-01-29T12:21:42.780+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_dag.order_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [queued]>
[2025-01-29T12:21:42.781+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-01-29T12:21:42.799+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): order_Load_redshift> on 2025-01-29 12:17:52.370778+00:00
[2025-01-29T12:21:42.808+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2898) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T12:21:42.810+0000] {standard_task_runner.py:72} INFO - Started process 2900 to run task
[2025-01-29T12:21:42.810+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'order_Load_redshift', 'manual__2025-01-29T12:17:52.370778+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpwfg3_jj8']
[2025-01-29T12:21:42.812+0000] {standard_task_runner.py:105} INFO - Job 87: Subtask order_Load_redshift
[2025-01-29T12:21:42.876+0000] {task_command.py:467} INFO - Running <TaskInstance: main_dag.order_Load_redshift manual__2025-01-29T12:17:52.370778+00:00 [running]> on host ae52aba2dca2
[2025-01-29T12:21:42.996+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='itsMe!!' AIRFLOW_CTX_DAG_ID='main_dag' AIRFLOW_CTX_TASK_ID='order_Load_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T12:17:52.370778+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T12:17:52.370778+00:00'
[2025-01-29T12:21:42.997+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T12:21:44.738+0000] {logging_mixin.py:190} INFO - Data loaded successfully into table!
[2025-01-29T12:21:44.739+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T12:21:44.754+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T12:21:44.755+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=order_Load_redshift, run_id=manual__2025-01-29T12:17:52.370778+00:00, execution_date=20250129T121752, start_date=20250129T122142, end_date=20250129T122144
[2025-01-29T12:21:44.797+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T12:21:44.818+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T12:21:44.821+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
